### PR TITLE
Information governance changes

### PR DESCRIPTION
**Pull request by gkelly900**
Hi both. I've made quite a few deletions and some changes here, as briefly discussed with Olivia. Some of the things of note:

- Scrapping data movement and technical migration forms for all data movements. It doesn't look like people are using these anyway. This means we are saying it is ok to put any *non-personal* data on the platform without any extra admin.
- Passing off responsibility from the AP team to the data privacy team when movements contain personal data, while hopefully making it clear that it is AP users' responsibility to know if their data contains personal info and contact the correct people if so. I think this is now the correct way of doing things but I am not sure how much oversight the AP team wish to retain on this. 

Please do suggest changes if you think this is the wrong advice.

### CODE REVIEW

**Review by olivialewis501 — APPROVED** [review]
I think this matches my understanding George - thanks for updating. I'd just like to run this past Jon as IAO to make sure he's happy with us removing this section from the guidance. @jonr10 can you have a quick look

**Comment by rossjones** [comment]
My only concern would be that we'd have no record of the data movement at all, but if you're suggesting people aren't submitting them anyway then I guess it doesn't matter. I'm okay with the change, but I'd hope we've got longer term plans for strengthening our data management and making it more rigorous.

**Comment by gkelly900** [comment]
Thanks Ross. Yes apparently last one was submitted in September and there have been dozens of buckets created since then. An alternative may be to ask users to describe the data they are going to put in a bucket when they create it in control panel. Perhaps a tick box confirming it doesn't contain personal info or they have the relevant DPIA. But realise that may be low priority given the other things the team have to do!

**Comment by calumabarnett** [comment]
Can we add something in about the new data movement form as people *should* be completing this when moving sensitive data.

Neil Aremband suggested something along the lines of:
> Complete a data movements form on OneTrust. To request access to OneTrust or for further information on how to complete the form please contact privacy@justice.gov.uk.

Generally, for users, it seems that expectations around data movements are not very clear at all.

**Review by rossjones — APPROVED** [review]

**Review by jonr10 — APPROVED** [review]
I'm happy with these changes - but agree with comments from others that we need to be adding a little more monitoring/robustness of data uploads to the AP - where that's not personal data. It may be helpful to have those check boxes that people mentioned. 

On the problem that despite this guidance being pretty clear I also think I should send an email to G5/G6s summarising our guidance and someone from the team do a session at the G6 SLT summarising as part of a wider comms piece

**Pull request merged**
