### PR TITLE
dbtools, Rdbtools and data access guidance

### PR DESCRIPTION
**Pull request by gkelly900**
Added:

- Where there are references to `dbtools`, I have added references to `Rdbtools` with a description of who maintains what
- A diagram that should display the flow diagram for data access drawn [here](https://drive.google.com/file/d/102NHlVpV_LAwWJBSNErk4y4-S6ink_9N/view?usp=sharing). You should be able to view and I think request edit access from me (if you want). Edits made to the diagram should show up in the guidance.

Changed:

- Home directories now has its own page as the structure didn't quite make sense to me

### CODE REVIEW

**Review by olivialewis501 — APPROVED** [review]
thanks - this is all really clear to me and agree with the logic.

On the diagram, i wonder if there should also be a branch for 'data isn't on the AP' and what to do then, which could include contacting data-engineering but also uploading their own data, and then could link through to the guidance on data governance?

**Review by rossjones — APPROVED** [review]
Much clearer

**Comment by gkelly900** [comment]
Cheers both. @olivialewis501 tried to update the diagram to include your suggestion but it started to look really messy, so I have added a line of text above instead.

**Review by olivialewis501 — APPROVED** [review]

**Comment by pjrh-moj** [comment]
Looks sensible to me!

**Review by pjrh-moj — APPROVED** [review]

**Review by mratford — APPROVED** [review]

**Pull request merged**
